name: Java CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: cd app && chmod +x gradlew

      - name: Build with Gradle
        working-directory: ./app
        run: ./gradlew build

      - name: Run Checkstyle
        working-directory: ./app
        run: ./gradlew checkstyleMain